openapi: 3.0.0
info:
  title: RB Abroad Shikshya Pvt Ltd API Swagger
  description: RB Abroad Shikshya Pvt Ltd API documentation
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Mero Vision
    url: https://merovision.com
    email: merovision720@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://api.rbabroads.com/
    description: server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Super Admin
  - name: Super Admin > Authentication
  - name: Super Admin > User Data
  - name: Super Admin > Site Setting
  - name: Super Admin > Master Data
  - name: Super Admin > Country Master Data
  - name: Super Admin > Country Master Data > Nepal
paths:
  /api/super-admin-login:
    post:
      tags:
        - Super Admin > Authentication
      summary: super admin login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: superadmin@gmail.com
                password:
                  type: string
                  example: password
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/user/1:
    get:
      tags:
        - Super Admin > User Data
      summary: show single user data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/site-settings:
    post:
      tags:
        - Super Admin > Site Setting
      summary: Store Site Setting
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                site_title:
                  type: string
                  example: hy
                app_logo:
                  type: string
                fav_icon:
                  type: string
                email:
                  type: string
                phone_no:
                  type: string
                mobile_no:
                  type: string
                address:
                  type: string
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Super Admin > Site Setting
      summary: show all site settings data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/master-data/genders:
    get:
      tags:
        - Super Admin > Master Data
      summary: gender master data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/master-data/country-list:
    get:
      tags:
        - Super Admin > Master Data
      summary: country list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/master-data/countries/nepal:
    get:
      tags:
        - Super Admin > Country Master Data > Nepal
      summary: Nepal Province with district list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/master-data/countries/nepal/province/districts/{district_id}:
    get:
      tags:
        - Super Admin > Country Master Data > Nepal
      summary: municipality list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: district_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
