openapi: 3.0.0
info:
  title: RB Abroad Shikshya Pvt Ltd API Swagger
  description: RB Abroad Shikshya Pvt Ltd API documentation
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Mero Vision
    url: https://merovision.com
    email: merovision720@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://api.rbabroads.com/
    description: server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: Super Admin
  - name: Super Admin > Authentication
  - name: Super Admin > User Data
  - name: Super Admin > Site Setting
  - name: Super Admin > Master Data
  - name: Super Admin > Country Master Data
  - name: Super Admin > Country Master Data > Nepal
  - name: Super Admin > Company
  - name: Super Admin > University Application Period
  - name: Super Admin > Universities
  - name: Super Admin > CMS
  - name: Super Admin > CMS > Contact Us
  - name: Super Admin > CMS > Blog
  - name: Website
  - name: Website > Contact Us
  - name: Website > Blog
paths:
  /api/super-admin-login:
    post:
      tags:
        - Super Admin > Authentication
      summary: super admin login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: superadmin@gmail.com
                password:
                  type: string
                  example: password
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/user/1:
    get:
      tags:
        - Super Admin > User Data
      summary: show single user data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/change-password:
    post:
      tags:
        - Super Admin > User Data
      summary: change password
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                  example: fdgg
                password:
                  type: integer
                  example: '12345678'
                password_confirmation:
                  type: integer
                  example: '12345678'
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/user/{id}:
    post:
      tags:
        - Super Admin > User Data
      summary: update user details
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Hancie Phago5
                profile_image:
                  type: string
                  format: binary
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/site-settings:
    post:
      tags:
        - Super Admin > Site Setting
      summary: Store Site Setting
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                site_title:
                  type: string
                  example: hy
                app_logo:
                  type: string
                fav_icon:
                  type: string
                email:
                  type: string
                phone_no:
                  type: string
                mobile_no:
                  type: string
                address:
                  type: string
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Super Admin > Site Setting
      summary: show all site settings data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/master-data/genders:
    get:
      tags:
        - Super Admin > Master Data
      summary: gender master data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/master-data/country-list:
    get:
      tags:
        - Super Admin > Master Data
      summary: country list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/master-data/education-levels:
    get:
      tags:
        - Super Admin > Master Data
      summary: education levels
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/master-data/countries/nepal:
    get:
      tags:
        - Super Admin > Country Master Data > Nepal
      summary: Nepal Province with district list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/master-data/countries/nepal/province/districts/{district_id}:
    get:
      tags:
        - Super Admin > Country Master Data > Nepal
      summary: municipality list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: district_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/company:
    get:
      tags:
        - Super Admin > Company
      summary: Company get api
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/company/{company_id}:
    get:
      tags:
        - Super Admin > Company
      summary: show single company details
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: company_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/company/1:
    post:
      tags:
        - Super Admin > Company
      summary: update company
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                company_name:
                  type: string
                  example: R.B. Abroad Shikshya Pvt. Ltd.
                email:
                  type: string
                phone_no:
                  type: string
                mobile_no:
                  type: string
                country:
                  type: string
                  example: Nepal
                province:
                  type: string
                district:
                  type: string
                municipality:
                  type: string
                street_address:
                  type: string
                  example: Bhadrapur Road, Birtamode
                vat_no:
                  type: integer
                  example: '654647567'
                registration_number:
                  type: integer
                  example: '54657657567'
                website:
                  type: string
                  example: rbabroads.com
                company_logo:
                  type: string
                  format: binary
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/application-periods:
    get:
      tags:
        - Super Admin > University Application Period
      summary: get the list of university application period
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/university:
    post:
      tags:
        - Super Admin > Universities
      summary: Create Universities
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                university_name:
                  type: string
                  example: Yorkville University - Toronto
                country:
                  type: string
                  example: Canada
                country_code:
                  type: string
                  example: CA
                province:
                  type: string
                  example: Ontario
                city:
                  type: string
                  example: Toronto
                university_logo:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Super Admin > Universities
      summary: Show all university list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/university/{slug}:
    get:
      tags:
        - Super Admin > Universities
      summary: show single university detail
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/cms/contact-us:
    get:
      tags:
        - Super Admin > CMS > Contact Us
      summary: show all contact us list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
        - name: pagination_limit
          in: query
          schema:
            type: integer
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/cms/contact-us/{contact_id}:
    delete:
      tags:
        - Super Admin > CMS > Contact Us
      summary: delete contact us data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: contact_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/cms/blogs:
    post:
      tags:
        - Super Admin > CMS > Blog
      summary: create blog
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: hy
                description:
                  type: string
                  example: dsfgsgd
                blog_image:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Super Admin > CMS > Blog
      summary: show all blog list
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: pagination_limit
          in: query
          schema:
            type: integer
          example: '5'
        - name: search_keyword
          in: query
          schema:
            type: string
          example: hy
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/super-admin/cms/blogs/{slug}:
    get:
      tags:
        - Super Admin > CMS > Blog
      summary: show single blog
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Super Admin > CMS > Blog
      summary: delete blog
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Super Admin > CMS > Blog
      summary: update blog
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: dfsgd
                description:
                  type: string
                  example: gdgdg
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/contact-us:
    post:
      tags:
        - Website > Contact Us
      summary: store contact us
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Hancie Phago
                email:
                  type: string
                  example: hanciephago@gmail.com
                mobile_no:
                  type: integer
                  example: '9825915122'
                subject:
                  type: string
                  example: hy
                message:
                  type: string
                  example: hy
      security:
        - noauthAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/blogs:
    get:
      tags:
        - Website > Blog
      summary: show all blog list
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: pagination_limit
          in: query
          schema:
            type: integer
          example: '5'
        - name: search_limit
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/blogs/{blog}:
    get:
      tags:
        - Website > Blog
      summary: show single blog details
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: blog
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
